### ISSUE TITLE
Skyblazer - FastROM necessary?

### ISSUE THREAD

**Issue by do-not-share-my-personal-information** [Krokodyl/krokodyl.github.io#1]
Hello. Is there really any slowdown with this game? kandowontu's created a FastROM patch for the official US release, but your translation hack seems to use SlowROM.

**Comment by Krokodyl** [comment]
This is the repo of my blog, please don't open issues here.
Anyway, don't open issues for messages that should have been a comment or a dm. That's not the purpose of issues.
Why would I base my patch on someone else's patch instead of a clean rom? If I do and they update theirs, mine could become instantly defective.

As for the game, I've not experienced any consequential slowdowns (just replayed the first half).
Shouldn't kandowontu be the person to ask about what stages or bosses his fastrom patch actually improves?
The patch note (https://www.romhacking.net/hacks/7636) states that the game is "painfully slow" and "laggy". That's the lie of someone who never played the game before. The note also says something about a sword (the hero fights with bare hands).
From what I can see in Mesen, the patch only improves loading times by about 15 frames between stages.
If you need that extra 1/4 of a second per stage, knock yourself out.
If someone wants to blindly convert every snes rom into fastrom, without stopping to think if they should, more power to them. I'm not touching that.
